techworkersco/twc-site-nl

- _i18n/en.yml
- _i18n/nl.yml
- change.md
This change:
- Adds a page with an Airtable questionnaire asking about 3 things ppl would like to change about their work. It's in EN only for now bc haven't had the time to set up bilingual options here.
- Links to this questionnaire page from the homepages (EN/NL) with a difficult-to-miss button
> Add page w/ questionnaire, link it from homepage

- _i18n/en.yml
- _i18n/nl.yml
This change removes the temporary button for gathering work issues from the homepage in both the EN and NL versions. This button had been added for the MozFest event in early June. As this event has now passed, we can remove this button again -- as discussed in this [Slack conversation](https://techworkersco.slack.com/archives/C06NYM3271D/p1719557456287469?thread_ts=1719305663.184519&cid=C06NYM3271D).
Btw it was also pointed out that the blurb generally could be better, which is totally valid! This is just to make this specific, limited fix.
> Remove temporary issue-gathering button EN, NL

- events.yml
This makes it possible to load events inside techworkerscoalition.org, when it is called in this loader https://github.com/techworkersco/twc-site/blob/master/_config.yml#L40 and https://github.com/techworkersco/twc-site/blob/f3dcf19642e5f149981f6091b6837184e50e5eed/_includes/events.html#L1
> Adding Dutch events so they can be consumed on mainstream website

- .prettierignore
Prettier doesn't like events.yml. It started failing recently, who knows why, but also we don't need it on that file (hopefully :sweat_smile:)
> Ignore events.yml for prettier - not needed

- .github/workflows/dependabot_automerge.yaml
Reduce human toil by automerging non-major dependabot updates.
If we want to make it "bombproof", we might need to force some PR [status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks) to ensure it can be built on netlify
> feat(gha): automerge non-major dependabot updates

- .github/dependabot.yaml
- .github/workflows/dependabot_automerge.yaml
Requires: #26 
Reason for monthly: reduce dependency update noise. This is a static site, so updating things to be on the bleeding edge is less important
Security dependabots still get checked as and when they come out, even with monthly selected
> Introduce monthly dependabot

- admin/config.yml
Docs are here: https://decapcms.org/docs/editorial-workflows/
TL;DR: This workflow enables drafts to be saved as pull requests, which can then be published (e.g. merges the PR). This means we can enable main push protection and status checks on PRs etc.
> This enables us to enable branch protection

- _events/biweekly-planning-meeting-10.md
- _events/biweekly-planning-meeting-11.md
- _events/biweekly-planning-meeting-8.md
- _events/biweekly-planning-meeting-9.md
I know twc-site-berlin uses "General Meeting". Also feels nice.
I think "Organizing" feels like a nicer word than "Planning" personally.
Also, giving numbers to the meetings so it's easier to organise in the admin/githubs. I took a guess at ~8 for the first one.
> Rename Planning => Organizing and give a number

- content/join-success/index.en.md
- content/join-success/index.nl.md
- layouts/_default/join-success.html
- layouts/partials/join-form.html
This change: 
- Adds a layout (`join-success`) for a landing page that the tech worker will land on once they've filled out the **Join** form
- Adds EN and NL post-join landing pages that use the `join-success` layout, with some info about next steps now that the tech worker has completed the form 
**TO DO:**
Setting this to **Draft** as I wasn't sure how to connect the success state of the form with this landing page? Any thoughts welcome or feel free to edit directly 🙂
> Add join success landing page

- content/_index.en.md
- content/_index.nl.md
- layouts/shortcodes/button.html
This change: 
- Updates the `button` shortcode, such that the link that you specify when the shortcode is used is language-relative, and you don't need to add a prefix to a specific language.
- Removes language-specific prefixes on two pages on which the button shortcode was used.
> (Fix) Button language-relative, update links on homepage

- netlify.toml
In this PR:
- Fix the 404 on the root page. e.g. https://techwerkers.nl/meow
- `nl ` is the default, so we only need redirects for `Accept-Language: en`
Note:
- We don't redirect /events/*, but realisitically we don't need to. These urls would be copy/pasted from person to person - e.g. no one is going accidentally type one of these event slugs by hand.
- `events` and `resources` and  `join` are the only root redirected paths at present. We need to remember to add more if we have more content types that people may type in.
- The default 404 is in dutch because that is the primary language of the site.
Chrome settings -> Search: Language -> Add dutch if not already there.
Note 1: Netlify only looks at the first language, so even if the language order is `fr,en`, it will give `nl` because …
> Redirect all root non-language resources to lang child

- content/resources/cao/index.en.md
- content/resources/cao/index.nl.md
- static/admin/config.yml
When adding decap in #62 I missed the feature image selector. Hugo is nice enough to detect "feature-*" as the feature image, but this will let people upload files directly via the CMS instead without having to rely on filenames.
Also, minor tweak to make last modified date to not be required.
Can be accessed here too: https://deploy-preview-66--twc-site-nl.netlify.app/admin/#/ (Note, the image won't show up since decap is accessing the resources from `main` instead of from this branch).
> Add feature image support to decap cms

- static/admin/config.yml
git-gateway looks deprecated by netlify: https://docs.netlify.com/security/secure-access-to-sites/git-gateway/
The way it worked: We stored a PAT token in netlify. When people logged into the CMS, they were logging into netlify. Netlify would then use that PAT token to commit the changes. This meant we could give people access to netlify, instead of the git repo. It also meant people didn't have to have a git account. Reality is that the editing group likely isn't large, and we can get those people to create github accounts.
Also: Enable open authoring. Forks and commits PRs for anyone: https://decapcms.org/docs/open-authoring/
:point_up: This will mean anyone can go to https://techwerkers.nl/admin, and they will be able to create new records. It will fork the repo into their github …
> Use different backend for CMS

- config/_default/languages.en.toml
- config/_default/languages.nl.toml
This change adds the social links to our Mastodon & Bluesky accounts to the footer.
> Add bluesky, mastodon socials to footer

- .prettierignore
- config/_default/config.toml
- content/events/2025-04-07/index.en.md
- content/events/2025-04-07/index.nl.md
- content/events/2025-04-08/index.en.md
- content/events/2025-04-08/index.nl.md
- content/events/2025-04-11/index.en.md
- content/events/2025-04-11/index.nl.md
- content/events/2025-04-15/index.en.md
- content/events/2025-04-15/index.nl.md
- content/events/2025-04-21/index.en.md
- content/events/2025-04-21/index.nl.md
- content/events/2025-04-23/index.en.md
- content/events/2025-04-23/index.nl.md
- content/events/2025-04-25/index.en.md
- content/events/2025-04-25/index.nl.md
- content/events/2025-05-01/index.en.md
- content/events/2025-05-01/index.nl.md
- content/events/2025-05-19/index.en.md
- content/events/2025-05-19/index.nl.md
- content/events/_index.en.md
- content/events/_index.nl.md
- layouts/_default/events.yaml
- static/admin/config.yml
Lots of "TIL" for me here.
Hugo wants to have output formats "per content". e.g. we have a main _index collection page for events, and current we render this in HTML (and also JSON, and RSS xml aswell!)
So what we "needed" here is a new output format for yaml - and then telling the events page we also want to have a YAML output. We could define yaml output for the entire site, however hugo starts to complain since we don't have a global yaml. Fun facts: https://techwerkers.nl/en/index.xml <-- we have a RSS feed for our homepage at present :sweat_smile: 
So this PR:
And bonuses:
:brain: At some point in the future we could enable an `ics` output format. Then we could actually render an `ics` (calendar) file for each event, and put a link on the page for people to add it to their calendars …
> Add events.yaml for global site

- content/events/2025-05-12/index.en.md
- content/events/2025-05-12/index.nl.md
- content/events/2025-05-26/index.en.md
- content/events/2025-05-26/index.nl.md
- content/events/2025-06-09/index.en.md
- content/events/2025-06-09/index.nl.md
This change adds events for organizing meetups on 12 and 26 May, and 9 June, to keep the events list populated. Merging w/o review as it just adds more events of the same type that we already have in the calendar many times.
> Add upcoming organizing events

- .prettierignore
There isn't any way to control the output of the content from decap, and it all "Just works" normally. And it looks like there isn't a way to configure decap output frontmatter to be prettier compliant, so :shrug:.
Alternative is to get prettier to just run from a github action and commit itself, but meh? It's a bit of messing around for not much benefit, so if someone else is keen to make that work, all good.
> Ignore content for prettier, decap and prettier don't play togethermn

- content/posts/dag-van-de-arbeid-looptocht-1-mei-2025/index.en.md
- content/posts/dag-van-de-arbeid-looptocht-1-mei-2025/index.nl.md
- i18n/en.yaml
- i18n/nl.yaml
- layouts/_partials/home/page.html
- layouts/_partials/recent-posts.html
Some small suggestions for the [home page news PR](https://github.com/techworkersco/twc-site-nl/pull/98):
- Place the new section higher up on the home page, before the events list. 
- Motivation: 'Recent news' sounds like something that's OK show first, and it provides some differentiation in the visual rhythm (news => image + txt, events => plain list, resources => image + txt).
_Preview of changed order_
- Adjust some wording to make it sound slightly more natural in Dutch, with corresponding changes in English.
- Add a period at end of news post summary to make it look tidier in the display.
> Swap placement of news on homepage

- layouts/_default/events.yaml
The goal of this pr is to get "NL" added as prefix to the events in the /en/index/events.yaml file so that they import into the main twc calendar with location clear.
> add NL prefix to events listing

- layouts/_default/events.yaml
This breaks yaml syntax and moves url/title to same line
`url: https://deploy-preview-108--twc-site-nl.netlify.app/en/events/2025-02-03/- title:"NL: Organizing for Power | Session #1"` 
Reverts techworkersco/twc-site-nl#108
> Revert "add NL prefix to events listing"

- layouts/_default/events.yaml
This modifies all titles of events generated in the YAML file at https://deploy-preview-111--twc-site-nl.netlify.app/en/events/index.yaml (or http://techwekers.nl/en/events/index.yaml on production) to have a `Netherlands:` string prefix which adds more context for events like "Organizing meetup" on the global events page of TWC. 
Here is the older pull request that loads Dutch events into global website https://github.com/techworkersco/twc-site/pull/432
> Prefix Netherlands for global event consumer

- content/events/2025-07-08/index.en.md
- content/events/2025-07-08/index.nl.md
This change postpones the AI reading group (originally scheduled for 8 July) to a future date to be confirmed. Merging directly because it's a purely textual change.
> Add postponement note to AI reading group session
